//------------------------------------------------------------------------------
// <auto-generated>
//   This code was generated by a tool.
//   Runtime Version:4.0.30319.17929
//
//   Changes to this file may cause incorrect behavior and will be lost if
//   the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OmlExport {
  using System;
  using System.Collections.Generic;
  using Microsoft.SolverFoundation.Services;
  
  
  public class DefaultModel {
    
    private Model model;
    
    private SolverContext context;
    
    private Decision w0;
    
    private Decision w1;
    
    private Decision w2;
    
    public DefaultModel() {
      this.context = SolverContext.GetContext();
      this.model = this.context.CreateModel();
      this.model.Name = "DefaultModel";
      // Create a Decision for W0
      this.w0 = new Decision(Domain.Real, "W0");
      this.model.AddDecision(this.w0);
      // Create a Decision for W1
      this.w1 = new Decision(Domain.Real, "W1");
      this.model.AddDecision(this.w1);
      // Create a Decision for W2
      this.w2 = new Decision(Domain.Real, "W2");
      this.model.AddDecision(this.w2);
      // Add Constraint for R0
      this.model.AddConstraint("R0", ((-1D * Model.Sum(this.w0, (-0.243044D * this.w1), (-0.678714D * this.w2))) 
              >= 1D));
      // Add Constraint for R1
      this.model.AddConstraint("R1", ((-1D * Model.Sum(this.w0, (0.690143D * this.w1), (-0.534921D * this.w2))) 
              >= 1D));
      // Add Constraint for R2
      this.model.AddConstraint("R2", ((1D * Model.Sum(this.w0, (0.674723D * this.w1), (0.831948D * this.w2))) 
              >= 1D));
      // Add Constraint for R3
      this.model.AddConstraint("R3", ((-1D * Model.Sum(this.w0, (-0.887092D * this.w1), (0.079283D * this.w2))) 
              >= 1D));
      // Add Constraint for R4
      this.model.AddConstraint("R4", ((-1D * Model.Sum(this.w0, (0.90985D * this.w1), (-0.427897D * this.w2))) 
              >= 1D));
      // Add Constraint for R5
      this.model.AddConstraint("R5", ((1D * Model.Sum(this.w0, (-0.357123D * this.w1), (0.085013D * this.w2))) 
              >= 1D));
      // Add Constraint for R6
      this.model.AddConstraint("R6", ((1D * Model.Sum(this.w0, (0.842992D * this.w1), (0.79588D * this.w2))) 
              >= 1D));
      // Add Constraint for R7
      this.model.AddConstraint("R7", ((1D * Model.Sum(this.w0, (0.931106D * this.w1), (0.787058D * this.w2))) 
              >= 1D));
      // Add Constraint for R8
      this.model.AddConstraint("R8", ((1D * Model.Sum(this.w0, (0.333565D * this.w1), (0.969998D * this.w2))) 
              >= 1D));
      // Add Constraint for R9
      this.model.AddConstraint("R9", ((1D * Model.Sum(this.w0, (-0.893644D * this.w1), (0.354697D * this.w2))) 
              >= 1D));
      // Add Goal for OBJxFUNC
      this.model.AddGoal("OBJxFUNC", GoalKind.Minimize, Model.Sum(0.5D, Model.Product(0.5D, this.w1, this.w1), Model.Product(0.5D, this.w2, this.w2)));
    }
    
    public virtual Model Model {
      get {
        return this.model;
      }
    }
    
    public virtual SolverContext Context {
      get {
        return this.context;
      }
    }
    
    public virtual Decision W0 {
      get {
        return this.w0;
      }
    }
    
    public virtual Decision W1 {
      get {
        return this.w1;
      }
    }
    
    public virtual Decision W2 {
      get {
        return this.w2;
      }
    }
    
    public virtual void Solve() {
      this.context.Solve();
    }
  }
}
